import type { mapType } from './type'

export const mapsData: mapType[] = [
    { name: '北京', value: 170, height: 1.7 },
    { name: '天津', value: 95, height: 0.95},
    { name: '河北', value: 115, height: 1.15},
    { name: '山西', value: 40, height: 0.4},
    { name: '内蒙古', value: 30, height: 0.3},
    { name: '辽宁', value: 90, height: 0.9},
    { name: '吉林', value: 70, height: 0.7},
    { name: '黑龙江', value: 20, height: 0.2},
    { name: '上海', value: 210, height: 2.1},
    { name: '江苏', value: 120, height: 1.2},
    { name: '浙江', value: 110, height:  1.1},
    { name: '安徽', value: 100, height: 1},
    { name: '福建', value: 120, height: 1.2},
    { name: '江西', value: 150, height: 1.5},
    { name: '山东', value: 70, height: 0.7},
    { name: '河南', value: 70, height: 0.7},
    { name: '湖北', value: 132, height: 1.32},
    { name: '湖南', value: 120, height: 1.2},
    { name: '重庆', value: 130, height: 1.3},
    { name: '四川', value: 70, height: 0.7},
    { name: '贵州', value: 110, height: 1.1},
    { name: '云南', value: 40, height: 0.4},
    { name: '西藏', value: 10, height: 0.1},
    { name: '陕西', value: 80, height: 0.8},
    { name: '甘肃', value: 60, height: 0.6},
    { name: '青海', value: 100, height: 1},
    { name: '宁夏', value: 70, height: 0.7},
    { name: '新疆', value: 20, height: 0.2},
    { name: '广东', value: 180, height: 1.8},
    { name: '广西', value: 130, height: 1.3},
    { name: '海南', value: 100, height: 1},
    { name: '台湾', value: 124, height: 1.24},
    { name: '香港', value: 60, height: 0.6},
    { name: '澳门', value: 80, height: 0.8},
];